default_stages: [ commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile', 'black']
        exclude: >-
          (?x)^(
          .*__init__\.py$
          )

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types_or: [python, pyi]
        args: ["--line-length", "120", "-t", "py310"]
      - id: black-jupyter
        name: black-jupyter
        entry: black
        language: python
        types_or: [python, pyi, jupyter]
        args: ["--line-length", "120", "-t", "py310"]
        additional_dependencies: [".[jupyter]"]